apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: zamn
  data:
  - secretKey: "value"
    remoteRef:
      key: kv-v2/kubernetes/test
      property: secret_key

 
