apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://11.11.11.7:8200"
      path: "kv-v2"
      caBundle: "your-cert"
      #   insecureSkipVerify: true
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      auth:
        jwt:
          path: "homelab-k8s-jwt"
          role: "just-a-few"
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "eso-tokens"
            audiences:
              - vault
            expirationSeconds: 5
